/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SloButton {
        /**
          * Optional CSS class to add to the button
         */
        "class"?: string;
        /**
          * Whether the button is disabled
         */
        "disabled": boolean;
        /**
          * The button text content
         */
        "text": string;
        /**
          * The button type (button, submit, reset)
         */
        "type": 'button' | 'submit' | 'reset';
    }
}
declare global {
    interface HTMLSloButtonElement extends Components.SloButton, HTMLStencilElement {
    }
    var HTMLSloButtonElement: {
        prototype: HTMLSloButtonElement;
        new (): HTMLSloButtonElement;
    };
    interface HTMLElementTagNameMap {
        "slo-button": HTMLSloButtonElement;
    }
}
declare namespace LocalJSX {
    interface SloButton {
        /**
          * Optional CSS class to add to the button
         */
        "class"?: string;
        /**
          * Whether the button is disabled
         */
        "disabled"?: boolean;
        /**
          * The button text content
         */
        "text"?: string;
        /**
          * The button type (button, submit, reset)
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface IntrinsicElements {
        "slo-button": SloButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "slo-button": LocalJSX.SloButton & JSXBase.HTMLAttributes<HTMLSloButtonElement>;
        }
    }
}
