/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SloButton {
        /**
          * Specifies whether the button should be outlined or filled.
         */
        "appearance": 'outline' | 'filled';
        /**
          * Disables the button, preventing interaction.
         */
        "disabled": boolean;
        /**
          * Controls the loading state of the button
         */
        "loading": boolean;
        /**
          * Specifies the type of the button (e.g., 'submit', 'button', 'reset').
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Specifies the variant/style of the button (e.g., 'primary', 'secondary').
         */
        "variant": 'primary' | 'secondary';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSloButtonElement extends Components.SloButton, HTMLStencilElement {
    }
    var HTMLSloButtonElement: {
        prototype: HTMLSloButtonElement;
        new (): HTMLSloButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "slo-button": HTMLSloButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SloButton {
        /**
          * Specifies whether the button should be outlined or filled.
         */
        "appearance"?: 'outline' | 'filled';
        /**
          * Disables the button, preventing interaction.
         */
        "disabled"?: boolean;
        /**
          * Controls the loading state of the button
         */
        "loading"?: boolean;
        /**
          * Specifies the type of the button (e.g., 'submit', 'button', 'reset').
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Specifies the variant/style of the button (e.g., 'primary', 'secondary').
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "slo-button": SloButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "slo-button": LocalJSX.SloButton & JSXBase.HTMLAttributes<HTMLSloButtonElement>;
        }
    }
}
