/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BasicCard {
        "card_title": string;
        "description": string;
        "disabled": boolean;
        "href": string;
        "summary": string;
        "type": string;
    }
    interface SloAccordion {
    }
    interface SloAccordionItem {
        "disabled": boolean;
        "heading": string;
    }
}
declare global {
    interface HTMLBasicCardElement extends Components.BasicCard, HTMLStencilElement {
    }
    var HTMLBasicCardElement: {
        prototype: HTMLBasicCardElement;
        new (): HTMLBasicCardElement;
    };
    interface HTMLSloAccordionElement extends Components.SloAccordion, HTMLStencilElement {
    }
    var HTMLSloAccordionElement: {
        prototype: HTMLSloAccordionElement;
        new (): HTMLSloAccordionElement;
    };
    interface HTMLSloAccordionItemElement extends Components.SloAccordionItem, HTMLStencilElement {
    }
    var HTMLSloAccordionItemElement: {
        prototype: HTMLSloAccordionItemElement;
        new (): HTMLSloAccordionItemElement;
    };
    interface HTMLElementTagNameMap {
        "basic-card": HTMLBasicCardElement;
        "slo-accordion": HTMLSloAccordionElement;
        "slo-accordion-item": HTMLSloAccordionItemElement;
    }
}
declare namespace LocalJSX {
    interface BasicCard {
        "card_title"?: string;
        "description"?: string;
        "disabled"?: boolean;
        "href"?: string;
        "summary"?: string;
        "type"?: string;
    }
    interface SloAccordion {
    }
    interface SloAccordionItem {
        "disabled"?: boolean;
        "heading"?: string;
    }
    interface IntrinsicElements {
        "basic-card": BasicCard;
        "slo-accordion": SloAccordion;
        "slo-accordion-item": SloAccordionItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "basic-card": LocalJSX.BasicCard & JSXBase.HTMLAttributes<HTMLBasicCardElement>;
            "slo-accordion": LocalJSX.SloAccordion & JSXBase.HTMLAttributes<HTMLSloAccordionElement>;
            "slo-accordion-item": LocalJSX.SloAccordionItem & JSXBase.HTMLAttributes<HTMLSloAccordionItemElement>;
        }
    }
}
